# Generated by Django 3.0.6 on 2020-05-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='BlogView',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
