# Generated by Django 3.0.6 on 2020-05-12 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='photo',
        ),
        migrations.AddField(
            model_name='fact',
            name='testimony',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
    ]
