# Generated by Django 3.0.6 on 2020-05-11 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='doctor/'),
            preserve_default=False,
        ),
    ]
